{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.kaden.cloudMusic;

  mountArguments =
    [
      "${cfg.package}/bin/rclone"
      "mount"
      cfg.remote
      cfg.mountPoint
      "--config=${cfg.configFile}"
      "--vfs-cache-mode=${cfg.vfsCacheMode}"
      "--vfs-cache-max-size=${cfg.cacheSize}"
      "--vfs-cache-max-age=${cfg.cacheMaxAge}"
      "--cache-dir=${cfg.cacheDir}"
      "--dir-cache-time=${cfg.dirCacheTime}"
      "--poll-interval=${cfg.pollInterval}"
      "--buffer-size=${cfg.bufferSize}"
    ]
    ++ lib.optional cfg.readOnly "--read-only"
    ++ cfg.extraArgs;
in
{
  options.services.kaden.cloudMusic = {
    enable = lib.mkEnableOption "an rclone-mounted cloud music library";

    remote = lib.mkOption {
      type = lib.types.str;
      example = "music-drive:Music";
      description = ''
        Rclone remote and path to mount. The named remote must already exist in
        the mutable rclone configuration file.
      '';
    };

    mountPoint = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/Music/Cloud";
      defaultText = lib.literalExpression ''"''${config.home.homeDirectory}/Music/Cloud"'';
      description = "Absolute path where the music library is mounted.";
    };

    configFile = lib.mkOption {
      type = lib.types.str;
      default = "${config.xdg.configHome}/rclone/rclone.conf";
      defaultText = lib.literalExpression ''"''${config.xdg.configHome}/rclone/rclone.conf"'';
      description = ''
        Mutable rclone configuration containing the remote and its OAuth
        token. This file is deliberately not generated by Home Manager.
      '';
    };

    cacheDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.xdg.cacheHome}/rclone/music";
      defaultText = lib.literalExpression ''"''${config.xdg.cacheHome}/rclone/music"'';
      description = "Directory used for rclone's VFS cache.";
    };

    cacheSize = lib.mkOption {
      type = lib.types.str;
      default = "30G";
      description = "Maximum size of the VFS cache.";
    };

    cacheMaxAge = lib.mkOption {
      type = lib.types.str;
      default = "168h";
      description = "Maximum age of an unused cached file.";
    };

    dirCacheTime = lib.mkOption {
      type = lib.types.str;
      default = "72h";
      description = "How long rclone caches directory entries.";
    };

    pollInterval = lib.mkOption {
      type = lib.types.str;
      default = "1m";
      description = "How frequently rclone checks Drive for remote changes.";
    };

    bufferSize = lib.mkOption {
      type = lib.types.str;
      default = "16M";
      description = "Per-open-file in-memory read buffer.";
    };

    vfsCacheMode = lib.mkOption {
      type = lib.types.enum [
        "off"
        "minimal"
        "writes"
        "full"
      ];
      default = "full";
      description = "Rclone VFS cache mode.";
    };

    readOnly = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Mount the remote read-only.";
    };

    extraArgs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "--log-level=INFO" ];
      description = "Additional arguments appended to the rclone mount command.";
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.rclone;
      defaultText = lib.literalExpression "pkgs.rclone";
      description = "Rclone package used by the mount service.";
    };

    extraPackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = with pkgs; [
        beets
        strawberry
      ];
      defaultText = lib.literalExpression "with pkgs; [ beets strawberry ]";
      description = "Music library applications installed with the service.";
    };
  };

  config = lib.mkMerge [
    # Keep the client available for the initial `rclone config` bootstrap even
    # before a remote exists and the mount service can safely be enabled.
    { home.packages = [ cfg.package ]; }

    (lib.mkIf cfg.enable {
      assertions = [
        {
          assertion = builtins.match "[^:]+:.*" cfg.remote != null;
          message = "services.kaden.cloudMusic.remote must look like an rclone remote, for example music-drive:Music";
        }
        {
          assertion = lib.hasPrefix "/" cfg.mountPoint;
          message = "services.kaden.cloudMusic.mountPoint must be an absolute path";
        }
        {
          assertion = lib.hasPrefix "/" cfg.cacheDir;
          message = "services.kaden.cloudMusic.cacheDir must be an absolute path";
        }
        {
          assertion = lib.hasPrefix "/" cfg.configFile;
          message = "services.kaden.cloudMusic.configFile must be an absolute path";
        }
      ];

      home.packages = cfg.extraPackages;

      systemd.user.services.rclone-music = {
        Unit = {
          Description = "Mount cloud music library with rclone";
          Documentation = [ "https://rclone.org/commands/rclone_mount/" ];
          After = [ "network-online.target" ];
          ConditionPathExists = cfg.configFile;
        };

        Service = {
          Type = "notify";
          Environment = [ "PATH=${lib.makeBinPath [ pkgs.fuse3 ]}" ];
          ExecStartPre = lib.escapeShellArgs [
            "${pkgs.coreutils}/bin/mkdir"
            "-p"
            cfg.mountPoint
            cfg.cacheDir
          ];
          ExecStart = lib.escapeShellArgs mountArguments;
          ExecStop = lib.escapeShellArgs [
            "${pkgs.fuse3}/bin/fusermount3"
            "-u"
            cfg.mountPoint
          ];
          Restart = "on-failure";
          RestartSec = "5s";
          TimeoutStopSec = "30s";
        };

        Install.WantedBy = [ "default.target" ];
      };
    })
  ];
}
