{ config, inputs, pkgs, ... }:

let
  dotfiles = inputs.dotfiles;
  onedarkWallpapers = inputs.onedark-wallpapers;
  zshEnv =
    builtins.replaceStrings
      [ ''. "$HOME/.cargo/env"'' ]
      [ ''[ -r "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"'' ]
      (builtins.readFile "${dotfiles}/zsh/.zshenv");
  waybarConfig =
    builtins.replaceStrings
      [
        "\"tray\",\n        \"custom/hyprwhspr\""
        ",\n    \"include\": [\n        \"/home/k/.config/waybar/hyprwhspr-module.jsonc\"\n    ]"
      ]
      [
        "\"tray\""
        ""
      ]
      (builtins.readFile "${dotfiles}/waybar/config.jsonc");
  waybarStyle =
    builtins.replaceStrings
      [ ''@import "/usr/lib/hyprwhspr/config/waybar/hyprwhspr-style.css";'' ]
      [ "" ]
      (builtins.readFile "${dotfiles}/waybar/style.css");
  electronFlags =
    (builtins.readFile "${dotfiles}/electron/electron-flags.conf")
    + ''
      --force-dark-mode
    '';
  hyprlandMonitorsLua = ''
    -- Generated by nwg-displays on 2026-06-18 at 13:31:27. Do not edit manually.

    hl.monitor({
        output = "desc:Lenovo Group Limited 0x4146",
        mode = "3840x2400@60.0",
        position = "2876x1634",
        scale = 2.0
    })
  '';
  hyprlandMonitorsConf = ''
    # Generated by nwg-displays on 2026-06-18 at 13:31:27. Do not edit manually.

    monitor=desc:Lenovo Group Limited 0x4146,3840x2400@60.0,2876x1634,2.0
  '';
  oldHyprlandInlineMonitors = builtins.concatStringsSep "\n" [
    ''-- Converted from source = ~/.config/hypr/monitors.conf''
    ''hl.monitor({ output = "desc:Lenovo Group Limited 0x4146", mode = "3840x2400@60.0", position = "2876x1634", scale = 2.0 })''
    ''hl.monitor({ output = "desc:ARZ ARZOPA-315", mode = "3840x2160@60.0", position = "0x0", scale = 1.5 })''
    "hl.monitor({"
    "\toutput = \"desc:Samsung Electric Company Odyssey G61SD HNAX901424\","
    "\tmode = \"2560x1440@120.0\","
    "\tposition = \"2560x194\","
    "\tscale = 1.0,"
    "})"
    ""
  ];
  hyprlandConfig =
    builtins.replaceStrings
      [
        ''hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")''
        ''hl.env("QT_STYLE_OVERRIDE", "Adwaita-Dark")''
        oldHyprlandInlineMonitors
      ]
      [
        ''hl.env("QT_QPA_PLATFORMTHEME", "adwaita")''
        ''hl.env("QT_STYLE_OVERRIDE", "adwaita-dark")''
        ''require("monitors")''
      ]
      (builtins.readFile "${dotfiles}/hyprland/hyprland.lua");
  ghosttyConfig =
    builtins.replaceStrings
      [
        "/bin/zsh"
        "font-size = 6"
      ]
      [
        "${pkgs.zsh}/bin/zsh"
        "font-size = 12"
      ]
      (builtins.readFile "${dotfiles}/ghostty/config");
in
{
  xdg.configFile = {
    "aerospace".source = "${dotfiles}/aerospace";
    "aerospace-swipe".source = "${dotfiles}/aerospace-swipe";
    "alacritty".source = "${dotfiles}/alacritty";
    "electron-flags.conf".text = electronFlags;
    "fontconfig/fonts.conf".source = "${dotfiles}/fontconfig/fonts.conf";
    "fuzzel".source = "${dotfiles}/fuzzel";
    "ghostty/config".text = ghosttyConfig;
    "ghostty/themes".source = "${dotfiles}/ghostty/themes";
    "hypr/hypridle.conf".source = "${dotfiles}/hyprland/hypridle.conf";
    "hypr/hyprland.lua".text = hyprlandConfig;
    "hypr/hyprlock.conf".source = "${dotfiles}/hyprland/hyprlock.conf";
    "hypr/macchiato.conf".source = "${dotfiles}/hyprland/macchiato.conf";
    "hypr/monitors.conf".text = hyprlandMonitorsConf;
    "hypr/monitors.lua".text = hyprlandMonitorsLua;
    "hypr/workspaces.conf".source = "${dotfiles}/hyprland/workspaces.conf";
    "hypr/xdph.conf".source = "${dotfiles}/hyprland/xdph.conf";
    "karabiner".source = "${dotfiles}/karabiner";
    "kdeglobals".source = "${dotfiles}/kde/kdeglobals";
    "kitty".source = "${dotfiles}/kitty";
    "nvim".source = "${dotfiles}/nvim";
    "opencode/agent".source = "${dotfiles}/opencode/agent";
    "opencode/bun.lock".source = "${dotfiles}/opencode/bun.lock";
    "opencode/opencode.json".source = "${dotfiles}/opencode/opencode.jsonc";
    "opencode/opencode.jsonc".source = "${dotfiles}/opencode/opencode.jsonc";
    "opencode/package.json".source = "${dotfiles}/opencode/package.json";
    "opencode/prompts".source = "${dotfiles}/opencode/prompts";
    "opencode/tool".source = "${dotfiles}/opencode/tool";
    "sketchybar".source = "${dotfiles}/sketchybar";
    "starship".source = "${dotfiles}/starship";
    "sway".source = "${dotfiles}/sway";
    "swaylock".source = "${dotfiles}/swaylock";
    "tmux".source = "${dotfiles}/tmux";
    "vim/.vimrc".source = "${dotfiles}/vim/.vimrc";
    "waybar/config.jsonc".text = waybarConfig;
    "waybar/style.css".text = waybarStyle;
    "hypr/hyprpaper.conf".text = ''
      wallpaper {
          monitor =
          path = ${onedarkWallpapers}/os/od_nixos.png
          fit_mode = cover
      }

      splash = false
      ipc = off
    '';
  };

  programs.zsh = {
    dotDir = "${config.xdg.configHome}/zsh";
    envExtra = zshEnv;
    initContent = builtins.readFile "${dotfiles}/zsh/.zshrc";
  };
}
